library(tidyverse)
recat_cargolab = function(Cargo.laboral){
  x = data.frame(x = Cargo.laboral)
  x = x %>%
    mutate(x = chartr('ÁÉÍÓÚÀÈÌÒÙ','AEIOUAEIOU',toupper(x))) %>%
    mutate(Cargo.laboral.recat = case_when(
      str_detect(x,'((DOC|PROF)+.+INNOV+.+PEDAG)|((DOC|PROF)+.+(AIP|INNOV))|(PIP|AIP)') ~ 'PROFESOR DE INNOVACION PEDAGOGICA - PIP',
      str_detect(x,'ADMIN|OFI[N]*CI|SECRE|(PERS+.+ADMIN)|PLANILL|VIGILA|PERSON|REMUNER') ~ 'PERSONAL ADMINISTRATIVO',
      str_detect(x,'GEST+.+PEDAG') ~ 'JEFE DE GESTION PEDAGOGICA',
      str_detect(x,'CO[O]*RD+.+ACAD') ~ 'COORDINADOR ACADEMICO',
      str_detect(x,'CO[O]*RD+.+(SEHO|HOSP)') ~ 'COORDINADOR SEHO',
      str_detect(x,'ESPECI+.+(SEHO|HOSP)') ~ 'ESPECIALISTA SEHO',
      str_detect(x,'(SEHO|HOSP)') ~ 'OTROS CARGOS SEHO',
      str_detect(x,'ESPECI+.+( DRE| UGEL| GRE)') ~ 'ESPECIALISTA DRE/UGEL',
      str_detect(x,'PSIC') ~ 'PSICOLOGA',
      str_detect(x,'PROMOT') ~ 'PROMOTOR',
      str_detect(x,'DIRECT+.+( DRE| UGEL| GRE)') ~ 'DIRECTOR DRE/UGEL',
      str_detect(x,'UGEL|DRE|DEGP|DGP') ~ 'OTROS CARGOS EN DRE/UGEL',
      str_detect(x,'(DOC|PROF)+.+EBA') ~ 'DOCENTE EBA',
      str_detect(x,'EBA|FT') ~ 'OTROS CARGOS EN EBA',
      str_detect(x,'(DOC|PROF)+.+(EBE|ESPECI)') ~ 'DOCENTE EBE',
      str_detect(x,'ESPECI+.+(EBE|ESPECI)') ~ 'ESPECIALISTA EBE',
      str_detect(x,'EBE|AGEBRE') ~ 'OTROS CARGOS EN EBE',
      str_detect(x,'(EST)+.+EIB') ~ 'DOCENTE EIB',
      str_detect(x,'ESPECI+.+(EIB)') ~ 'ESPECIALISTA EIB',
      str_detect(x,'EIB') ~ 'OTROS CARGOS EN EIB',
      str_detect(x,'FORM(AD|)+.+TUT') ~ 'FORMADOR TUTOR',
      str_detect(x,'(DOC|PROF)+.+PRONOE') ~ 'DOCENTE PRONOEI',
      str_detect(x,'(PROM)+.+PRONOE') ~ 'PROMOTOR PRONOEI',
      str_detect(x,'(CO[O]*RD)+.+PRONOE') ~ 'COORDINADOR PRONOEI',
      str_detect(x,'PRONOE') ~ 'OTROS CARGOS EN PRONOEI',
      str_detect(x,'(^DIRECT)+.+(INICI|PRIM|SEC)') ~ 'DIRECTOR',
      str_detect(x,'(^DIRECT)') ~ 'DIRECTOR',
      str_detect(x,'^SU(B|D|)') ~ 'SUBDIRECTOR',
      str_detect(x,'DIRECT') ~ 'DIRECTOR',
      str_detect(x,'(DOC|PROF)+.+INI+.+PRIM+.+SEC') ~ 'DOCENTE DE INICIAL, PRIMARIA Y SECUNDARIA',
      str_detect(x,'(DOC|PROF)+.+PRIM+.+SEC') ~ 'DOCENTE DE PRIMARIA Y SECUNDARIA',
      str_detect(x,'(DOC|PROF|^ED)+.+IN*C') ~ 'DOCENTE DE INICIAL',
      str_detect(x,'INIC') ~ 'OTROS CARGOS EN INICIAL',
      str_detect(x,'(DOC|PROF)+.+PRIM') ~ 'DOCENTE DE PRIMARIA',
      str_detect(x,'PRIM') ~ 'OTROS CARGOS EN PRIMARIA',
      str_detect(x,'(DOC|PROF)+.+SEC') ~ 'DOCENTE DE SECUNDARIA',
      str_detect(x,'SEC') ~ 'OTROS CARGOS EN SECUNDARIA',
      str_detect(x,'(A)*TET|(TERR+.+TECNO)|TERR') ~ 'ATET',
      str_detect(x,'ESTUD|PRACT') ~ 'ESTUDIANTE',
      str_detect(x,'(DOC|PROF)+.+((TEC+.+PROD)|(ETP)|EPT|E\\.T\\.P)') ~ 'DOCENTE ETP',
      str_detect(x,'ETP|(TEC+.+PROD)') ~ 'OTROS CARGOS EN ETP',
      str_detect(x,'CIST') ~ 'COORDINADOR DE INNOVACION Y SOPORTE TECNOLOGICO - CIST',
      str_detect(x,'INNOV|DAIP') ~ 'DOCENTE DE AULA DE INNOVACION PEDAGOGICA - DAIP',
      str_detect(x,'AUXIL') ~ 'AUXILIAR',
      str_detect(x,'(CO[O]*R+.+(RER|RURAL))|(C*+RER)') ~ 'COORDINADOR RER',
      str_detect(x,'CO[O]*R+.+(RED)') ~ 'COORDINADOR RED',
      str_detect(x,'CO[O]*R+.+(CRFA)') ~ 'COORDINADOR CRFA',
      str_detect(x,'(CO[O]*R+.+PEDAG)') ~ 'COORDINADOR PEDAGOGICO',
      str_detect(x,'(DOC|PROF)+.+((INST+.+TECN)|IEST|IESP|SUPERIOR|INST)') ~ 'DOCENTE EN IEST/IESP',
      str_detect(x,'((INST+.+TECN)|IEST|IESP|EESPP)') ~ 'OTROS CARGOS EN IEST/IESP',
      str_detect(x,'ESPEC*+.+DE[ ]*VIDA') ~ 'ESPECIALISTA EN DEVIDA',
      str_detect(x,'(APOY|FACIL)*+.+DE[ ]*VIDA') ~ 'FACILITADOR/APOYO EN DEVIDA',
      str_detect(x,'(DOC|PROF)+.+(SAANEE)') ~ 'DOCENTE SAANEE',
      str_detect(x,'(CO[O]*RD)+.+(SAANEE)') ~ 'COORDINADOR SAANEE',
      str_detect(x,'(SAANEE)') ~ 'OTROS CARGOS SAANEE',
      str_detect(x,'JEF+.+LAB') ~ 'JEFE DE LABORATORIO',
      str_detect(x,'INDEP|CONSULT') ~ 'INDEPENDIENTE',
      str_detect(x,'MINEDU|DIGERE|DITE|(GEST+.+MACRO)') ~ 'ESPECIALISTA MINEDU',
      str_detect(x,'COMUNI|IMAGEN') ~ 'COMUNICADOR',
      str_detect(x,'FACIL') ~ 'FACILITADOR',
      str_detect(x,'CO[O]*R+.+(ODEC)') ~ 'COORDINADOR DRE/UGEL',
      str_detect(x,'DRE|UGEL|AGP|SIAG|EICE|ECEU') ~ 'OTROS CARGOS EN DRE/UGEL',
      str_detect(x,'(^SOPORT+.+(TECN|INFOR))|TIC|TECNO') ~ 'SOPORTE TIC',
      str_detect(x,'CO[O]*R') ~ 'COORDINADOR',
      str_detect(x,'^IE') ~ 'OTROS CARGOS EN LAS IIEE',
      str_detect(x,'NADA|MSC|NINGUN|DESEMPL|(SIN+.+CONT)|(NO+.+LABOR)|EGRES') ~ 'NINGUNO',
      str_detect(x,'(DOC|PROF|MAEST)') ~ 'OTROS DOCENTES',
      str_detect(x,'ACADE') ~ 'COORDINADOR ACADEMICO',
      T ~ 'OTROS CARGOS'
      ))
  return(x$Cargo.laboral.recat)
  }
